# Generated by Django 5.0.3 on 2024-03-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy_strings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тема')),
                ('main_field', models.TextField(verbose_name='Событие')),
                ('date', models.DateTimeField(verbose_name='Дата записи')),
            ],
        ),
    ]
